version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/usr/src/app # Mount the current directory to the container
    environment:
      - NODE_ENV=production # Set environment variable